[env:m5stack-atoms3]
platform = espressif32@6.10.0
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200
build_flags =
	-D WIFI_SSID=\"\"
	-D WIFI_PASSWORD=\"\"
	-D OTA_HOSTNAME=\"general-joy\"
	-D ESPNOW_CHANNEL=1
	; -D OTA_PASSWORD=\"your_ota_password\"
	; Pairing data is saved in SPIFFS:
	;   /roverc_peer.txt
	;   /bugc_peer.txt
	;   /mini4wd_peer.txt
	;   /roller485_peer.txt

[env:m5stack-atoms3-ota]
extends = env:m5stack-atoms3
upload_protocol = espota
upload_port = general-joy.local
; If OTA_PASSWORD is set, enable this too:
; upload_flags =
; 	--auth=your_ota_password
