[env:m5stick-c-plus]
platform = espressif32@6.10.0
board = m5stick-c
framework = arduino
monitor_speed = 115200
lib_deps =
	m5stack/M5StickCPlus@0.1.1
lib_ignore =
	M5StickC
build_flags =
	-D WIFI_SSID=\"\"
	-D WIFI_PASSWORD=\"\"
	-D OTA_HOSTNAME=\"bug-mecanum\"
	-D ESPNOW_CHANNEL=1
	-D BUGC_I2C_SDA=0
	-D BUGC_I2C_SCL=26
	-D BUGC_I2C_FREQ=400000
	-D BUGC_SPEED_SCALE=70
	-D BUGC_RUDDER_SCALE=45
	-D BUGC_MOTOR0_SIGN=1
	-D BUGC_MOTOR1_SIGN=-1
	-D BUGC_MOTOR2_SIGN=1
	-D BUGC_MOTOR3_SIGN=-1
	-D USE_M5STICKC_PLUS
	; -D OTA_PASSWORD=\"your_ota_password\"

[env:m5stick-c-plus-ota]
extends = env:m5stick-c-plus
upload_protocol = espota
upload_port = bug-mecanum.local
; If OTA_PASSWORD is set, enable this too:
; upload_flags =
; 	--auth=your_ota_password
